services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bm-services_container
    image: bm-services
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/queen/certs:/etc/nginx/certs:ro
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: