services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bm-services_container
    restart: unless-stopped
    image: bm-services
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "8080:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
